import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const PROMPT =
  "Create a NEW photorealistic fashion photo of the person in the FIRST image wearing the clothing item from the SECOND image. IMPORTANT: Do NOT overlay, paste, or copy pixels from either input image. The output MUST be a newly generated image (not the original person photo and not the original clothing photo). Preserve the person's identity (face, hair, skin tone) and keep the background/lighting consistent with the FIRST image. Replace the person's current outfit entirely. The garment must fit naturally to the body with realistic fabric drape, folds, shadows, and correct perspective.";

// Call Lovable AI Gateway
async function callLovableGateway(
  apiKey: string,
  modelImage: string,
  clothImage: string
): Promise<{ image?: string; status?: number; error?: string }> {
  const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "google/gemini-3-pro-image-preview",
      messages: [
        {
          role: "user",
          content: [
            { type: "text", text: PROMPT },
            { type: "image_url", image_url: { url: modelImage } },
            { type: "image_url", image_url: { url: clothImage } },
          ],
        },
      ],
      modalities: ["image", "text"],
    }),
  });

  if (!response.ok) {
    return { status: response.status, error: await response.text() };
  }

  const data = await response.json();
  const image = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
  return { image };
}

// Call Google Gemini API directly as fallback
async function callGeminiDirect(
  apiKey: string,
  modelImage: string,
  clothImage: string
): Promise<{ image?: string; error?: string }> {
  console.log("Attempting fallback to direct Gemini API...");

  // Convert data URLs to inline_data format for Gemini
  const extractBase64 = (dataUrl: string) => {
    const match = dataUrl.match(/^data:([^;]+);base64,(.+)$/);
    if (!match) throw new Error("Invalid data URL format");
    return { mimeType: match[1], data: match[2] };
  };

  const modelImageData = extractBase64(modelImage);
  const clothImageData = extractBase64(clothImage);

  // Use the paid model (gemini-2.0-flash) to avoid free-tier quota limits
  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              { text: PROMPT },
              { inline_data: modelImageData },
              { inline_data: clothImageData },
            ],
          },
        ],
        generationConfig: {
          responseModalities: ["TEXT", "IMAGE"],
        },
      }),
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    console.error("Gemini direct API error:", response.status, errorText);
    return { error: `Gemini API error: ${response.status}` };
  }

  const data = await response.json();
  // Extract image from Gemini response
  const parts = data.candidates?.[0]?.content?.parts || [];
  for (const part of parts) {
    if (part.inlineData?.mimeType?.startsWith("image/")) {
      const base64 = part.inlineData.data;
      const mimeType = part.inlineData.mimeType;
      return { image: `data:${mimeType};base64,${base64}` };
    }
  }

  return { error: "No image generated by Gemini" };
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { clothImage, modelImage } = await req.json();

    if (!clothImage || !modelImage) {
      return new Response(
        JSON.stringify({ error: "Both cloth and model images are required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY");

    if (!LOVABLE_API_KEY && !GEMINI_API_KEY) {
      throw new Error("No API keys configured");
    }

    let generatedImage: string | undefined;

    // Try Lovable Gateway first
    if (LOVABLE_API_KEY) {
      console.log("Trying Lovable AI Gateway...");
      const result = await callLovableGateway(LOVABLE_API_KEY, modelImage, clothImage);

      if (result.image) {
        generatedImage = result.image;
      } else if (result.status === 402 || result.status === 429) {
        console.log(`Lovable Gateway returned ${result.status}, checking for fallback...`);

        // Fallback to user's Gemini key if available
        if (GEMINI_API_KEY) {
          const fallbackResult = await callGeminiDirect(GEMINI_API_KEY, modelImage, clothImage);
          if (fallbackResult.image) {
            generatedImage = fallbackResult.image;
          } else if (fallbackResult.error) {
            return new Response(
              JSON.stringify({ error: fallbackResult.error }),
              { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
            );
          }
        } else {
          // No fallback available
          const errorMsg =
            result.status === 402
              ? "AI credits exhausted. Add a GEMINI_API_KEY secret as fallback, or add workspace credits."
              : "Rate limited. Please try again later.";
          return new Response(
            JSON.stringify({ error: errorMsg }),
            { status: result.status, headers: { ...corsHeaders, "Content-Type": "application/json" } }
          );
        }
      } else {
        console.error("Lovable Gateway error:", result.error);
        return new Response(
          JSON.stringify({ error: "Failed to process virtual try-on" }),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
    } else if (GEMINI_API_KEY) {
      // Only Gemini key available
      const result = await callGeminiDirect(GEMINI_API_KEY, modelImage, clothImage);
      if (result.image) {
        generatedImage = result.image;
      } else {
        return new Response(
          JSON.stringify({ error: result.error || "Failed to generate image" }),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
    }

    // The model sometimes echoes an input image for complex cases; treat that as a failure.
    if (generatedImage === clothImage || generatedImage === modelImage) {
      console.warn("Try-on generation returned an input image (echo).");
      return new Response(
        JSON.stringify({
          error:
            "Try-on failed (the AI returned one of the input images). Please try a simpler garment photo (clear front view, plain background) or a different model photo.",
        }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!generatedImage) {
      return new Response(
        JSON.stringify({ error: "No image was generated" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    return new Response(
      JSON.stringify({ image: generatedImage }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Virtual try-on error:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
